<?php

/**
 * Do not edit this file manually, generated by the Yeoman Phalcon generator
 * Register application modules
 */
$this->registerModules(array(
	'<%= module.slug %>' => array(
		'className' => '\<%= project.namespace %>\<%= module.namespace %>\Module',
		'path' => __DIR__ . '/../modules/<%= module.slug %>/Module.php'
	)
));
